# Generated by Django 6.1.1 on 2026-09-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="numReviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
